name: Docker Image Build

env:
  IMAGE_NAME: akshithachittanoori276/web-ready
  MAJOR_MINOR: "3.1"
  BUILD_NUMBER: $GITHUB_RUN_NUMBER

on:
  push:
    branches: [ master,US-624164]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 7 * * *'

jobs:
  docker-login:
    name: Login to DockerHub
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  test:
    name: Container Tests
    runs-on: ubuntu-latest
    if: always()
    needs: docker-login
    steps:
    - name: Check out working repository
      uses: actions/checkout@v2

    - name: Run Container Tests
      run: |
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
        chmod +x container-structure-test-linux-amd64
        sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
        make test
        

  push:
    name: Push to DockerHub
    if: always()
    runs-on: ubuntu-latest
    needs: [scan, test]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out working repository
        uses: actions/checkout@v2
      - name: Push image to dockerhub 
        run: make push
